  x1min = min(bb1[0], bb2[0])
    x1max = max(bb1[0], bb2[0])
    x2min = min(bb1[2], bb2[2])
    x2max = max(bb1[2], bb2[2])
    y1min = min(bb1[1], bb2[1])
    y1max = max(bb1[1], bb2[1])
    y2min = min(bb1[3], bb2[3])
    y2max = max(bb1[3], bb2[3])
    # print(f"x1 min and max is {x1min} , {x1max}")
    # print(f"x2 min and max is {x2min} , {x2max}")
    # print(f"y1 min and max is {y1min} , {y1max}")
    # print(f"y2 min and max is {y2min} , {y2max}")
    # print(f"x1min < x2max  is  {x1min < x2max}")
    # print(f"x2min > x1max  is  {x2min > x1max}")
    # print(f"y1min < y2max  is  {y1min < y2max}")
    # print(f"y2min > y1max  is  {y2min > y1max}")
    # isOverlapping = (x1min < x2max and x2min < x1max and y1min < y2max and y2min < y1max)
    isOverlapping = (x1min < x2max and x2min > x1max and y1min < y2max and y2min > y1max)
